version: '3'
services:

    nginx:
      image: nginx
      build: requirements/nginx/
      container_name: nginx
      ports:
          - "443:443"
      restart: always

    mariadb:
      image: mariadb
      build: requirements/mariadb/
      container_name: mariadb
      restart: always
      environment:
                DATABASE_NAME: ${DATABASE_NAME}
                DB_ROOT_PWD: ${DB_ROOT_PWD}
                DATABASE_ADMIN: ${DATABASE_ADMIN}
                DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}